AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*.rb"

Layout/LineLength:
  Exclude:
    - "test/**/*.rb"

Style/Documentation:
  Enabled: false
